### ISSUE TITLE
Potential pull request

### ISSUE THREAD

**Issue by attebury** [jimniels/teamcolors#14]
I've [forked your project](https://github.com/attebury/teamcolors/tree/dev) and am using a few grunt plugins to create PNG fallbacks and am experimenting with the creation of league webfonts. It's still a work in progress, but I'm getting close to decision points and your input would help.

Is this something you'd be interested in merging back into this project or should I just plan to keep those changes in a separate fork?

If you'd prefer to keep it separate, I have minified the SVGs and can contribute those back if helpful
![tc-nfl-med-sprite](https://f.cloud.github.com/assets/149034/2107407/f9783fca-8fc8-11e3-8290-decba5b0ace0.png)
.

**Comment by jimniels** [comment]
Note: the repo is now running on Gulp.
