### ISSUE TITLE
Atlanta United and Minnesota United FC

### ISSUE THREAD

**Issue by edhenderson** [jimniels/teamcolors#68]
Are joining the MLS in 2017. Here is the data I'm using but I dont have "official" colours (extracted with Tineye) and no logos:

```json
{
  "name": "Minnesota United FC",
  "type": "MLS",
  "internalId": "MIN",
  "colours": ["#e2e3df", "#222", "#9bcce3"]
},
{
  "name": "Atlanta United FC",
  "type": "MLS",
  "internalId": "ATL",
  "colours": ["#252021", "#918254", "#7e000b"]
}
```

Pick the bones as you wish or ignore for now.

**Comment by jimniels** [comment]
Thanks for noting that these teams were missing. I added them while also updating the DC United logo. Since we don't have "official" colors, I just went with the colors I could get from the `.svg` logo. Changes are live now at http://jim-nielsen.com/teamcolors

Thanks again!
