### ISSUE TITLE
EPL out of date

### ISSUE THREAD

**Issue by edhenderson** [jimniels/teamcolors#70]
Using http://www.espnfc.us/english-premier-league/23/table as reference against your data file, it seems that you are a wee bit out of date (last years teams maybe?)

## need to remove
- Aston Villa
- Newcastle United
- Queens Park Rangers

## need to add
- Watford
- Middlesbrough
- Bournemouth

Once I source some colours, I'll let you know.

**Comment by edhenderson** [comment]
- Watford - "colours": ["#fbee23", "#ed2127", "#000"]
- Middlesborough - "colours": ["#f00", "#fff", "#0a0d26"]
- Bournemouth - "colours": ["#f00", "#fff"]

**Comment by jimniels** [comment]
Are these colors approximations?

**Comment by edhenderson** [comment]
I colour picked them from their Wikipedia pages, so yes.

**Comment by jimniels** [comment]
Great. Thanks for noting the league updates (I'm not a big follower of EPL personally). Changes are up!
